### ISSUE TITLE
Add a GUI

### ISSUE THREAD

**Issue by dennis95** [dennis95/dennix#20]
We should be able to run multiple graphical applications at the same time rather than just one fullscreen application.

**Comment by dennis95** [comment]
This would also give us something interesting to show in screenshots (#18).

**Comment by 00p513-dev** [comment]
Maybe X Windows could be ported? Of course once #22 #23 and #24 are fixed

**Comment by dennis95** [comment]
I have created a little GUI demo in the [gui-demo](https://github.com/dennis95/dennix/tree/gui-demo) branch.

It supports multiple windows, transparency, resizing, and each window has a working close button.

What is still missing to make the GUI useful, is the ability for applications to create their own windows inside the GUI and a way for the GUI to forward events to those applications. That can be implemented once sockets (#23) exist.

![gui-demo](https://user-images.githubusercontent.com/11199027/100764797-09d7ac00-33f7-11eb-8a5f-8bb2573bc655.png)

**Comment by dennis95** [comment]
The [gui](https://github.com/dennis95/dennix/tree/gui) branch now contains a working GUI compositor.
Applications can create windows within the GUI and receive events about key presses, mouse movements, etc.
Further changes will be required before it is ready to be merged into the master branch.

![gui](https://user-images.githubusercontent.com/11199027/103362883-14e73000-4aba-11eb-9b96-0fe197f80e2f.png)

**Comment by dennis95** [comment]
The GUI has now been merged into the master branch.
![gui](https://user-images.githubusercontent.com/11199027/123304055-c2de0f00-d51e-11eb-9170-304061327ff5.png)
