### ISSUE TITLE
Port Dennix to x86_64

### ISSUE THREAD

**Issue by dennis95** [dennis95/dennix#3]
Dennix should support x86_64.

**Comment by NeroReflex** [comment]
This project is great for educational purpouses. Adding x86_64 wuold be an overkill that adds too much complexity to andò educational OS.
Nontheless there are more important issues to solve and better things to do,  like drivers....

**Comment by NeroReflex** [comment]
*an

**Comment by dennis95** [comment]
The x86_64 port has now been merged into the master branch,
Dennix now supports both the i686 and the x86_64 architecture.
