### ISSUE TITLE
Use on replit?

### ISSUE THREAD

**Issue by 17lwinn** [dennis95/dennix#31]
Repl.it is able to run QEMU, which have been used to help other users make their own OSes. But is there anyway this OS could be ported to repl? or perhaps make a guide to do so? 

I think it should work, but it would be really great if it could be done as it means many others can see and use the OS without needing to do anything locally.

**Comment by dennis95** [comment]
I'm not really familiar with repl.it but if it runs QEMU, it should be as simple as downloading a release image (or compiling one yourself) and then loading it in QEMU.

However I would expect it to be quite slow compared to running QEMU on a local machine.

**Comment by 17lwinn** [comment]
I'll give it a try!  thanks!
