### ISSUE TITLE
CI Builds provide ready to use ISO

### ISSUE THREAD

**Issue by MarcoCicognani** [dennis95/dennix#33]
Hi man!
you have made great strides, congratulations.

As said in the title, It would be nice if the CI provides the built ISO of DennixOS.

It isn't difficult to upload the image at the end, [as I do in my CI](https://github.com/MarcoCicognani/MeetixOS/blob/dda3621e290c722e75c895a306edc3eb0a55f98a/.github/workflows/BuildAll.yml#L47)

Keep going!
I want to play with your OS

**Comment by dennis95** [comment]
Thanks for that suggestion. Done in 8e47a19936c63cc3abe76cfb7241dc07717448c1.
First set of iso images is available at https://github.com/dennis95/dennix/actions/runs/2783384679.
